Repository githubschool/nov-13, pull requests merged in 2018-11, with the labels that each got.

#8 Changing caption
  _posts/0000-01-09-arvindsbabu.md
Labels: enhancement

#17 jaishaunik - Changing caption text
  _posts/0000-01-06-jaishaunik.md
Labels: enhancement

#15 Changed the caption
  _posts/0000-01-20-ambpac1220.md
Labels: good first issue

#14 Change caption mkumarkr slide
  _posts/0000-01-14-mkumarkr.md
Labels: enhancement

#22 Added a caption to an image!
  _posts/0000-01-15-vinaymbharadwaj.md
Labels: enhancement, good first issue

#20 changed the caption as my first commit
  _posts/0000-01-04-tej1599.md
Labels: good first issue

#16 Change caption brianamarie slide
  _posts/0000-01-21-brianamarie.md
Labels: enhancement

#21 Change caption shahulirshad slide
  _posts/0000-01-21-shahulirshad.md
Labels: enhancement

#13 my first commit, changed caption
  _posts/0000-01-07-bhatchetan.md
Labels: enhancement

#34 Editing the intro file which is common
  _posts/0000-01-01-intro.md
Labels: good first issue
